fancybox: false ## If you want to use fancybox please set the value to true.
duoshuo: ## Your duoshuo_shortname, e.g. username
disqus: daiyiblorg ## TODO
google_search: false ## Use Google search, true/false.
baidu_search: ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: ## Use a jQuery-based local search engine, true/false.
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
shareto: false ## If you want to use the share button please set the value to true.
busuanzi: false ## If you want to use Busuanzi page views please set the value to true.
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.

menu:
  - page: about
    directory: http://daiyi.co
  - page: ideas and feelings
    directory: .
  - page: art/photo blog
    directory: http://daiyi.tumblr.com
  - page: "@daiyitastic"
    directory: https://twitter.com/daiyitastic
  - page: rss
    directory: rss2.xml

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - profile
  - category
  - tag
  # - search TODO


profile:
  photo: img/patagonia.jpg
  name: chris (daiyi!)
  url: http://daiyi.co
  about: 'coder, hitchhiker, alpinist; born in california and raised by the internet. yells when excited. yells all the time.'
  links:
    - title: twitter
      url: https://twitter.com/daiyitastic
    - title: github
      url: https://github.com/daiyitastic

timeline:
  - num: 1
    word: 2014/06/12-Start
  - num: 2
    word: 2014/11/29-XXX
  - num: 3
    word: 2015/02/18-DDD
  - num: 4
    word: More

# Static files
js: js
css: css

# Theme version
version: 0.0.1
